Feature/cz/order tracking system #189
CS308-Team17/online-store-frontend pull request #26
Opened 2024-11-25 21:54 UTC by CZunal

![image](https://github.com/user-attachments/assets/74882477-5022-4a55-8f33-aeb6e1a26871)
![image](https://github.com/user-attachments/assets/a3534011-aa74-438d-9066-80f73f976623)

2024-11-25 21:57 UTC, CZunal commented
Şu butonlar arasında geçiş yapınca, hangisinde olduğunu gösterecek bir şey yok şuan onu ekleyecem

2024-11-26 09:18 UTC, gorkemtopcu commented on src/features/customer/orders/OrderView.js
> +  if (loading) {
iki return yerine if'i bir sonraki returnun icerisine tasir misin? Kod duplicate olmus boyle. Istersen genel bir loading componenti da hazirlaybilirsin butun projede ortak kullanilabilen.

2024-11-26 09:19 UTC, gorkemtopcu commented on src/features/customer/orders/OrderView.js
> +      {filteredOrders.length ? (
Hatta istersen bunu da bir componenta tasi okumasi kolay olsun burayi. OrderList.js gibi bir seyden bahsediyorum

2024-11-26 09:36 UTC, gorkemtopcu commented on src/features/customer/orders/OrderView.js
Ilk kez uygulamaya giren kullaniciya tanimli bir order olmadigi zaman burasi hata atiyor yeni bir user acip burayi tekrar deneyebilir misin?

2024-11-26 09:41 UTC, gorkemtopcu commented on src/features/customer/orders/components/OrderViewNavbar.js
> +  const sortOrders = (criteria) => {
burada strategy pattern kullanabilir misin, soyle bir seyden bahsediyorum:
```import { useMemo } from "react";

const useFilterOrders = (orders) => {
  return useMemo(() => ({
    [StringConstants.PROCESSING]: () => orders.filter((order) => order.orderStatus === "PROCESSING"),
    [StringConstants.IN_TRANSIT]: () => orders.filter((order) => order.orderStatus === "IN_TRANSIT"),
    [StringConstants.DELIVERED]: () => orders.filter((order) => order.orderStatus === "DELIVERED"),
    [StringConstants.CANCELLED]: () => orders.filter((order) => order.orderStatus === "CANCELLED"),
    [StringConstants.ALL]: () => [...orders],
  }), [orders]);
};

const sortOrders = (criteria) => {
  const filterStrategies = useFilterOrders(orders);
  const strategy = filterStrategies[criteria] || filterStrategies[StringConstants.ALL];
  const sortedOrders = strategy();

  setFilteredOrders(sortedOrders);
  setActiveFilter(criteria);
};
```

2024-11-26 09:43 UTC, gorkemtopcu commented on src/features/customer/orders/components/StatusTag.js
burayi da yine switchten kurtarsak nasil olur? soyle mesela
```
import React from "react";
import { Tag } from "antd";
import { CheckCircleOutlined, SyncOutlined, ClockCircleOutlined, CloseCircleOutlined } from "@ant-design/icons";
import StringConstants from "constants/StringConstants";

const statusMapping = {
  DELIVERED: {
    color: "green",
    icon: <CheckCircleOutlined />,
    label: StringConstants.DELIVERED,
  },
  IN_TRANSIT: {
    color: "blue",
    icon: <SyncOutlined spin />,
    label: StringConstants.IN_TRANSIT,
  },
  PROCESSING: {
    color: "orange",
    icon: <ClockCircleOutlined />,
    label: StringConstants.PROCESSING,
  },
  CANCELLED: {
    color: "red",
    icon: <CloseCircleOutlined />,
    label: StringConstants.CANCELLED,
  },
};

const StatusTag = ({ status }) => {
  const { color, icon, label } = statusMapping[status] || {
    color: "default",
    icon: null,
    label: StringConstants.UNKNOWN,
  };

  return (
    <Tag color={color} icon={icon} style={{ fontSize: "14px", padding: "5px 10px" }}>
      {label}
    </Tag>
  );
};

export default StatusTag;
```

2024-11-26 09:44 UTC, gorkemtopcu requested changes
Eline saglik knk, sadece order view'da bir null check yapmak lazim su an exception aliyoruz cunku

2024-11-26 09:57 UTC, CZunal commented on src/features/customer/orders/OrderView.js
> +  if (loading) {
![image](https://github.com/user-attachments/assets/73eb33e2-98ea-42c4-b203-6f22b3c4f4d0)
şu nasıl

2024-11-26 10:09 UTC, gorkemtopcu commented on src/features/customer/orders/OrderView.js
> +  if (loading) {
Gayet okay bence bu

2024-11-26 10:12 UTC, gorkemtopcu approved these changes

2024-11-26 10:52 UTC, merged